spring.application.name=BucketS3
server.port=8081
aws.accessKey=ASIAU3LDGKASVPPAK2U5
aws.secretKey=QYxTKmoF8rxzQrIxJUHHfvUinNKdevWEx1r9Q78q
aws.sessionToken=IQoJb3JpZ2luX2VjEKb//////////wEaCXVzLXdlc3QtMiJHMEUCIQDwTZECP7cIoG2qa0UJycodJc4j0XPxO98DMQFP2GIE1AIgTIDVebqNy1sOdiy2sUpyzYRIwz351pScBilVDDEZYzoqugIITxAAGgwzMzM2MDQ4NjgxMzMiDGJbbK3omg4kpmdytiqXAjTTwnWAF7MnuJi4/8nuS/pLeLoiuoXuOqtQhsUGMzQbmauSfVIYlwwBH6CFL2TtI9ozFhAtJuB27Qh3bwkdzpA1dad62cv2Gxcw3yohRf3wqDY0yw4Xu9h1Tq3xMPgMHKqblB+eu0dTZTeYCUzB16J09EMTM1ufR+MV41agsyDl1UhCU3hkiSZR5vDLG3vbapgx0CPwZkg7VsTJ7UUlB2Rw3+wUDVFSHz+a5vVAiF2oDC+46jO0k+K5Dlfz5R2dXY+rgVg47yClEgXISBjIJCAAKiGSVZUS1mtRQu0xiO7a8Xk1pxu7KQgKzmx8K7KGE8sGAyw5xtZaUwYh+MdPowJoRnkrXHVFp4BRZKhg6F3p0V8EdEpZ+jCz3bXHBjqdAR6yPQrQIlb94wl7LPl42GxH/Bur4qOr+/1inbuIhnaAm+4LcBS90vvOkHt1zGXzHxa9r/1SR8dDrLKxdvwZY4Z9ZO1wl1piLrNZ20+wcJEKx9BRhr24tcMSd20FJRHFnTBf+voGGFuSNWGkVATVsWhxGMWJjblJbCHOLt2hYUSGb/LTiXse1HczNNhlhVcG0NVQWcXD3XLMgufiw4U=
# Tamanho máximo do arquivo
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.mvc.cors.allowed-origins=*
spring.mvc.cors.allowed-methods=GET,POST,DELETE
spring.mvc.cors.allowed-headers=*

aws.region=us-east-1
aws.s3.bucket=softwave-arquivos-prod
