spring.application.name=BucketS3
server.port=8081
aws.accessKey=ASIAU3LDGKAS23FW6KHB
aws.secretKey=9PrroijnPVH7n//EaMw1GBZ++9lEGkhlgxyRdhsO
aws.sessionToken=IQoJb3JpZ2luX2VjEB4aCXVzLXdlc3QtMiJHMEUCIQCGdsCGxRsXbcYeu3BjVh2D2nfWDcSYZhfw3wNKAragMAIgE8xcIZVGhiU48TAlno44GM1bDgd2nL2OZ8QuvsMIBloqwwII5///////////ARAAGgwzMzM2MDQ4NjgxMzMiDERKsW6E/6alaEOnQCqXAsYH2SjXH42GJXajVBLJCY0DpG8wXnojhJWj18rMaEIAomdfX+r+PXfl181ihJC0GYhCvqk2XA4Oykdl+P6m9VeFH4lnJ/YQqwyjwoGyDkU3ty921imGbmG5RyTjM5aOV2c5qgqM6LZkiI69BUrv6qvXjeRP9HiAFyOeWsk04LRniYMRqeSmT5KmtJbSsFvHZvYXkf+eoplkIEbI3UEEmi7isSCFh1J0bJ8YjUk42+mExd20M0uSyp93gYElkjiZfOrH2f6BzwchY2bFOjZKgLiFZLt9vaE3zohZB+5750sSzCMrs5rLIqU02Ot+VomodZcp77F7+xFk8p2NKT0MIN9k6ZqO715jOCH29KIosWvasxF0qmW5UTDNlLHJBjqdAYs2/4jlGr2NCWw0CKdCMHindwIXcZHldwv8393OX8ws1Phbk9wyyD7vSF7ngspAxXNtjqbyCRSkbeM3BIvKi6RcNiHp5tom92A/DNz0g417bMocoATlMNup3A48LIpBM+ATk8BUj7VCKR/D3xX17rLHAZ05GUWftnVhsQ9NC4Amuy/m1mQ2YVoW98/nEpR5Wr7jsqbPs6FNDVC7v4Q=
# Tamanho máximo do arquivo
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.mvc.cors.allowed-origins=*
spring.mvc.cors.allowed-methods=GET,POST,DELETE
spring.mvc.cors.allowed-headers=*

aws.region=us-east-1
aws.s3.bucket=softwave-arquivos-prod
